const config=require('../config/config');
const mongoose=require('mongoose');
const db={};
mongoose.Promise=global.Promise;
mongoose.set('strictQuery',false);
db.mongoose=mongoose;
db.url=config.DB_URL;
db.fournisseurs= require('../api/models/Fournisseur.model')(mongoose);
db.users= require('../api/models/User.model')(mongoose);
db.articles= require('../api/models/Article.model')(mongoose);
module.exports=db;